### ISSUE TITLE
Can't open file

### ISSUE THREAD

**Issue by firebone3** [vvhg1/clp-keycaps#1]
![11](https://github.com/vvhg1/clp-keycaps/assets/143563193/699e4321-6bb5-415e-bb5e-1dd6e8722d96)

can't open stl file in fusion 360
and f3z also opens only MX Plug Mushroom v4 file

**Comment by vvhg1** [comment]
Which stl did you try to open?
Regarding the f3z files, regardless of which you try, it only opens the MX Plug Mushroom?

**Comment by vvhg1** [comment]
@firebone3 I disabled lfs, that should hopefully resolve the issue, can you confirm please?

**Comment by firebone3** [comment]
now files open normally. 
Thank you
